name: Test Release

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "develop"

jobs:
  create-release:
    name: Build and Create Tagged release
    runs-on: ubuntu-latest

    steps:
      - name: Install archive tools
        run: sudo apt install zip

      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.repository.default_branch }}

      - name: Get variables
        id: get_vars
        run: |
          echo '::set-output name=SHORT_SHA::$(git rev-parse --short HEAD)'
          echo '::set-output name=DATE::$(date +'%D')'

      - name: 'Setup node'
        uses: actions/setup-node@v3
        with:
          node-version: 17
          cache: 'npm'
          cache-dependency-path: web/package-lock.json

      - name: Install dependencies
        run: npm i
        working-directory: web

      - name: Run build
        run: npm run build
        working-directory: web
        env:
          CI: false

      - name: Bundle files
        run: |
          mkdir -p ./temp/esx_hud
          mkdir -p ./temp/esx_hud/web
          cp ./fxmanifest.lua ./temp/esx_hud
          cp -r ./{client,locales,server,stream,shared} ./temp/esx_hud
          cp -r ./web/dist ./temp/esx_hud/web/dist
          cd ./temp && zip -r ../esx_hud.zip ./esx_hud
      - name: Test Release
        uses: 'marvinpinto/action-automatic-releases@v1.2.1'
        id: auto_release
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          automatic_release_tag: "latest"
          title: '${{ env.RELEASE_VERSION }}'
          prerelease: true
          files: esx_hud.zip

        env:
          CI: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
